export type Resource = {
  id: string;
  title: string;
  description: string;
  url: string;
  province: string;
  category: string;
};

export const defaultResources: Resource[] = [
  {
    id: "guide-caregiving-essentials",
    title: "Caregiving Essentials Program (McMaster University)",
    description: "A free, self-paced course covering safety, communication, healthcare navigation, and mental health for caregivers.",
    url: "https://continuing.mcmaster.ca/programs/health-social-services/caregiving-essentials/?utm_source=chatgpt.com",
    province: "National",
    category: "Guide",
  },
  {
    id: "guide-carechannel",
    title: "CareChannel by Elizz (SE Health)",
    description: "Hundreds of short videos on medication management, mobility, dementia care, and stress reduction.",
    url: "https://carechannel.elizz.com/?utm_source=chatgpt.com",
    province: "National",
    category: "Self-Care",
  },
  {
    id: "guide-caremaker-foundation",
    title: "CareMakers Foundation",
    description: "Digital toolkits, guides, and connections to caregiver training and support organizations across Canada.",
    url: "https://caremakers.ca/caregivers/?utm_source=chatgpt.com",
    province: "National",
    category: "Guide",
  },
  {
    id: "guide-ontario-caregiver-organization",
    title: "Ontario Caregiver Organization",
    description: "Learn how to be recognized as an Essential Care Partner and join provincial caregiver support programs.",
    url: "https://ontariocaregiver.ca/essential-care-partner/overview/?utm_source=chatgpt.com",
    province: "Ontario",
    category: "Checklist",
  },
  {
    id: "guide-caregiver-handbook",
    title: "A Guide for Caregivers by Tanya Radford",
    description: "A Canada-wide handbook offering practical advice, emotional support strategies, and links to national resources.",
    url: "https://mscanada.ca/sites/default/files/documents/2024-09/1-original_2.pdf?utm_source=chatgpt.com",
    province: "National",
    category: "Guide",
  },
  {
    id: "financial-veterans",
    title: "Caregiver Recognition Benefit – Veterans Affairs Canada",
    description: "Monthly, tax-free payments for caregivers of eligible veterans.",
    url: "https://www.veterans.gc.ca/en",
    province: "National",
    category: "Financial",
  },
  {
    id: "financial-bc-guide",
    title: "Family Caregivers of BC – Financial Assistance Guide 2025",
    description: "Details on medical expense deductions, grants for equipment, and provincial supports.",
    url: "https://www.familycaregiversbc.ca/archives/20061?utm_source=chatgpt.com",
    province: "British Columbia",
    category: "Financial",
  },
  {
    id: "financial-federal",
    title: "Federal and Provincial Programs",
    description: "Overview of family benefits, disability supports, and caregiver assistance available across Canada.",
    url: "https://www.canada.ca/en/services/benefits/family.html",
    province: "National",
    category: "Guide",
  },
  {
    id: "financial-cdb",
    title: "Child Disability Benefit – Canada Revenue Agency",
    description: "A tax-free monthly payment to help families care for a child under 18 with a severe and prolonged disability.",
    url: "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/child-disability-benefit.html",
    province: "National",
    category: "Benefit",
  },
  {
    id: "community-ccce",
    title: "Canadian Centre for Caregiving Excellence (CCCE)",
    description: "Join advocacy groups, caregiver mentorship programs, and national initiatives.",
    url: "https://canadiancaregiving.org/impact/support-networks-and-knowledge-sharing/?utm_source=chatgpt.com",
    province: "National",
    category: "Community",
  },
  {
    id: "community-carers-canada",
    title: "Carers Canada",
    description: "Find caregiver coalitions, webinars, and community roundtables across Canada.",
    url: "https://carerscanada.ca/",
    province: "National",
    category: "Community",
  },
  {
    id: "community-von",
    title: "VON Caregiver Supports",
    description: "Access peer groups, one-on-one counselling, and local connections for emotional support.",
    url: "https://von.ca/en/von-care/caregiver-supports?utm_source=chatgpt.com",
    province: "National",
    category: "Service",
  },
  {
    id: "community-bc-complex-kids",
    title: "BC Complex Kids Society",
    description: "Advocacy and support for children and youth with medical complexity to help them thrive.",
    url: "https://www.bccomplexkids.ca/advocacy",
    province: "British Columbia",
    category: "Education",
  },
  {
    id: "community-results-org",
    title: "Results Org",
    description: "A national network of advocates committed to building solutions together.",
    url: "https://results.org",
    province: "National",
    category: "Community",
  },
  {
    id: "national-cdb",
    title: "Child Disability Benefit",
    description: "Tax-free monthly benefit for families caring for a child with a severe disability.",
    url: "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/child-disability-benefit.html",
    province: "National",
    category: "Government Benefits",
  },
  {
    id: "national-dtc",
    title: "Disability Tax Credit",
    description: "Non-refundable tax credit to reduce income tax and offset disability costs.",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit.html",
    province: "National",
    category: "Government Benefits",
  },
  {
    id: "national-ccce",
    title: "Canadian Centre of Caregiving Excellence",
    description: "National advocacy and knowledge network for caregivers and care providers.",
    url: "https://canadiancaregiving.org/",
    province: "National",
    category: "Advocacy Agencies",
  },
  {
    id: "national-ecc",
    title: "Every Canadian Counts",
    description: "Campaign for inclusive disability support and accessible services for all Canadians.",
    url: "https://everycanadiancounts.com/",
    province: "National",
    category: "Advocacy Agencies",
  },
  {
    id: "national-dwp",
    title: "Disability Without Poverty",
    description: "Grassroots movement ensuring people with disabilities have adequate income and supports.",
    url: "https://www.disabilitywithoutpoverty.ca/en",
    province: "National",
    category: "Advocacy Agencies",
  },
  {
    id: "national-ahnc",
    title: "Accessible Housing Network Canada",
    description: "Network advancing accessible housing policies and community solutions.",
    url: "https://www.accessiblehousingnetwork.org/",
    province: "National",
    category: "Advocacy Agencies",
  },
  {
    id: "national-cord",
    title: "Canadian Organization for Rare Diseases",
    description: "National alliance improving care, treatment, and support for people with rare disorders.",
    url: "https://www.raredisorders.ca/",
    province: "National",
    category: "Disability Support & Research",
  },
  {
    id: "national-autism",
    title: "Autism Canada",
    description: "Information, resources, and advocacy supporting autistic individuals and their families.",
    url: "https://www.autismcanada.org/",
    province: "National",
    category: "Disability Support & Research",
  },
  {
    id: "national-rhf",
    title: "Rick Hansen Foundation",
    description: "Programs that advance accessibility and inclusion across Canada.",
    url: "https://www.rickhansen.com/about-us/national-disability-initiative",
    province: "National",
    category: "Disability Support & Research",
  },
  {
    id: "national-easter-seals",
    title: "Easter Seals Canada",
    description: "Programs and services that empower Canadians living with disabilities.",
    url: "https://easterseals.ca/en/about-us/programs-and-services/",
    province: "National",
    category: "Disability Support & Research",
  },
  {
    id: "national-make-a-wish",
    title: "Make a Wish Canada",
    description: "Granting life-changing wishes for children with critical illnesses.",
    url: "https://makeawish.ca/",
    province: "National",
    category: "Grants & Wish Programs",
  },
  {
    id: "national-shine",
    title: "Shine Foundation",
    description: "Providing memorable experiences and support for children with severe chronic health challenges.",
    url: "https://www.shinefoundation.ca/",
    province: "National",
    category: "Grants & Wish Programs",
  },
  {
    id: "national-caremakers",
    title: "Petro Canada CareMakers Foundation",
    description: "Grantmaking and community initiatives that support caregivers nationwide.",
    url: "https://caremakers.ca/",
    province: "National",
    category: "Grants & Wish Programs",
  },
  {
    id: "bc-family-caregivers",
    title: "Family Caregivers of BC",
    description: "Peer support, education, and navigation help for caregivers in British Columbia.",
    url: "https://www.familycaregiversbc.ca",
    province: "British Columbia",
    category: "Government Program",
  },
  {
    id: "bc-inclusion",
    title: "Inclusion BC",
    description: "Advocacy and resources for people with intellectual and developmental disabilities.",
    url: "https://inclusionbc.org/",
    province: "British Columbia",
    category: "Advocacy",
  },
  {
    id: "alberta-caregivers",
    title: "Caregivers Alberta",
    description: "Coaching, courses, and financial navigation for caregivers across Alberta.",
    url: "https://www.caregiversalberta.ca/",
    province: "Alberta",
    category: "Community",
  },
  {
    id: "alberta-inclusion",
    title: "Inclusion Alberta",
    description: "Individual and family advocacy supporting inclusive communities.",
    url: "https://inclusionalberta.org/what-we-do/individual-family-advocacy/",
    province: "Alberta",
    category: "Advocacy",
  },
  {
    id: "manitoba-inclusion",
    title: "Inclusion Manitoba",
    description: "Resources and community supports for Manitobans with disabilities.",
    url: "https://www.aclmb.ca/",
    province: "Manitoba",
    category: "Community",
  },
  {
    id: "manitoba-government",
    title: "Government of Manitoba - Persons with Disabilities",
    description: "Information on services and supports available to Manitobans with disabilities.",
    url: "https://www.gov.mb.ca/fs/pwd/index.html",
    province: "Manitoba",
    category: "Government Program",
  },
  {
    id: "manitoba-childrens",
    title: "Children's disABILITY Services (Manitoba)",
    description: "Funding and service coordination for children with disabilities in Manitoba.",
    url: "https://www.gov.mb.ca/fs/cds/index.html",
    province: "Manitoba",
    category: "Government Program",
  },
  {
    id: "ontario-odc",
    title: "Ontario Disability Coalition",
    description: "Coalition advancing disability rights and inclusive policies in Ontario.",
    url: "https://odcoalition.com/",
    province: "Ontario",
    category: "Advocacy",
  },
  {
    id: "ontario-oco",
    title: "Ontario Caregiver Organization",
    description: "Programs, helpline, and resources supporting caregivers across Ontario.",
    url: "https://ontariocaregiver.ca/",
    province: "Ontario",
    category: "Community",
  },
  {
    id: "ontario-ponda",
    title: "Physicians of Ontario Neurodevelopmental Advocacy",
    description: "Clinician-led advocacy for children with neurodevelopmental disabilities.",
    url: "https://ponda.ca/",
    province: "Ontario",
    category: "Advocacy",
  },
  {
    id: "ontario-autism",
    title: "Ontario Autism Coalition",
    description: "Advocacy and community support for autistic children and their families.",
    url: "https://ontarioautismcoalition.com/",
    province: "Ontario",
    category: "Advocacy",
  },
  {
    id: "quebec-lappui",
    title: "L’APPUI (Proches aidants)",
    description: "Support and respite services for caregivers of older adults across Quebec.",
    url: "https://www.lappui.org/fr/",
    province: "Quebec",
    category: "Support",
  },
  {
    id: "quebec-sqdi",
    title: "Quebec Society for Intellectual Disabilities (SQDI)",
    description: "Advocacy, resources, and community inclusion for people with intellectual disabilities.",
    url: "https://www.sqdi.ca/en/",
    province: "Quebec",
    category: "Community",
  },
  {
    id: "new-brunswick-coalition",
    title: "New Brunswick Disability Coalition",
    description: "Network of organizations advancing disability rights and supports.",
    url: "https://www.nbcpd.org/",
    province: "New Brunswick",
    category: "Advocacy",
  },
  {
    id: "new-brunswick-caregiver-nb",
    title: "Caregiver NB",
    description: "Peer support, learning series, and navigation help for caregivers in New Brunswick.",
    url: "https://www.caregiversnb.org/",
    province: "New Brunswick",
    category: "Community",
  },
  {
    id: "nova-scotia-caregivers",
    title: "Caregivers Nova Scotia",
    description: "Education, support groups, and advocacy for caregivers throughout Nova Scotia.",
    url: "https://caregiversns.org/",
    province: "Nova Scotia",
    category: "Community",
  },
  {
    id: "nova-scotia-drc",
    title: "Disability Rights Coalition NS",
    description: "Advocating for inclusive services and ending institutionalization in Nova Scotia.",
    url: "https://www.disabilityrightscoalitionns.ca/",
    province: "Nova Scotia",
    category: "Advocacy",
  },
  {
    id: "pei-hospice",
    title: "Hospice PEI – Caregiver Support",
    description: "Programs and respite options for caregivers on Prince Edward Island.",
    url: "https://hospicepei.ca/caregiver-support-resources/",
    province: "Prince Edward Island",
    category: "Support",
  },
  {
    id: "pei-at-home",
    title: "At-Home Caregiver Benefit (PEI)",
    description: "Financial assistance to help caregivers provide care at home.",
    url: "https://www.princeedwardisland.ca/en/information/health-and-wellness/at-home-caregiver-benefit",
    province: "Prince Edward Island",
    category: "Benefit",
  },
  {
    id: "pei-association",
    title: "PEI Association for Community Living",
    description: "Resources and community inclusion programming for Islanders with disabilities.",
    url: "https://peiacl.org/",
    province: "Prince Edward Island",
    category: "Community",
  },
  {
    id: "newfoundland-cod",
    title: "Coalition of Persons with Disabilities NL (COD NL)",
    description: "Advocacy, policy, and programs for people with disabilities in Newfoundland and Labrador.",
    url: "https://codnl.ca/",
    province: "Newfoundland & Labrador",
    category: "Advocacy",
  },
  {
    id: "newfoundland-inclusion",
    title: "Inclusion Canada Newfoundland (Respite Program)",
    description: "Respite and support services for families of people with intellectual disabilities.",
    url: "https://www.inclusioncanadanl.ca/hotel-respite-program",
    province: "Newfoundland & Labrador",
    category: "Support",
  },
  {
    id: "newfoundland-report",
    title: "Caregivers Report (Citizens Rep Office)",
    description: "Insights and recommendations on supporting caregivers in Newfoundland and Labrador.",
    url: "https://www.citizensrep.nl.ca/pdfs/CaregiversReportOct5-2023.pdf",
    province: "Newfoundland & Labrador",
    category: "Research",
  },
  {
    id: "nunavut-nuability",
    title: "Nunavummi Disabilities Makinnasuaqtiit Society (Nuability)",
    description: "Community organization supporting Nunavut residents with disabilities.",
    url: "https://nuability.ca/",
    province: "Nunavut",
    category: "Community",
  },
  {
    id: "nunavut-acyf",
    title: "Arctic Child and Youth Foundation",
    description: "Programs supporting the wellbeing of children and youth across the Arctic.",
    url: "https://acyf.ca/",
    province: "Nunavut",
    category: "Support",
  },
  {
    id: "nwt-disability-council",
    title: "NWT Disability Council",
    description: "Supports, advocacy, and programs for people with disabilities in the Northwest Territories.",
    url: "https://www.nwtdc.net/",
    province: "Northwest Territories",
    category: "Advocacy",
  },
  {
    id: "nwt-true-north",
    title: "True North Aid",
    description: "Assistance and community development programs in northern communities.",
    url: "https://truenorthaid.ca/",
    province: "Northwest Territories",
    category: "Support",
  },
  {
    id: "nwt-inclusion",
    title: "Inclusion NWT",
    description: "Community living supports, respite, and advocacy in the Northwest Territories.",
    url: "https://www.inclusionnwt.ca/",
    province: "Northwest Territories",
    category: "Support",
  },
  {
    id: "yukon-inclusion",
    title: "Inclusion Yukon",
    description: "Inclusive programming, advocacy, and employment supports across Yukon.",
    url: "https://www.inclusionyukon.org/",
    province: "Yukon",
    category: "Community",
  },
];
